apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers # Required. Kafka broker connection setting
    value: "localhost:9092"
  - name: "topics"
    value: $Default
  - name: authType # Required.
    value: "none"
  - name: authRequired
    value: "true"
  - name: saslUsername
    value: "Admin"
  - name: saslPassword
    value: "Admin"
  - name: disableTls
    value: "true"